const City = (koreanCity) => {
    const cityMapping = {
        '서울': 'Seoul',
      '부산': 'Busan',
      '대구': 'Daegu',
      '인천': 'Incheon',
      '광주': 'Gwangju',
      '대전': 'Daejeon',
      '울산': 'Ulsan',
      '세종': 'Sejong',
      '경기도': 'Gyeonggi-do',
      '강원도': 'Gangwon-do',
      '충청북도': 'Chungcheongbuk-do',
      '충청남도': 'Chungcheongnam-do',
      '전라북도': 'Jeollabuk-do',
      '전라남도': 'Jeollanam-do',
      '경상북도': 'Gyeongsangbuk-do',
      '경상남도': 'Gyeongsangnam-do',
      '제주도': 'Jeju-do',
      '뉴욕': 'New York',
      '로스앤젤레스': 'Los Angeles',
      '런던': 'London',
      '파리': 'Paris',
      '도쿄': 'Tokyo',
      '오사카': 'Osaka',
      '후쿠오카': 'Fukuoka',
      '사포로': 'Sapporo',
      '교토': 'Kyoto',
      '구마모토': 'Kumamoto',
      '나라': 'Nara',
      '카가와': 'Kagawa',
      '토야마': 'Toyama',
      '히로시마': 'Hiroshima',
      '나하': 'Naha',
      '베를린': 'Berlin',
      '상파울로': 'Sao Paulo',
      '시드니': 'Sydney',
      '상하이': 'Shanghai',
      '모스크바': 'Moscow',
      '베이징': 'Beijing',
      '광저우': 'Guangzhou',
      '토론토': 'Toronto',
      '상트페테르부르크': 'Saint Petersburg',
      '뭄바이': 'Mumbai',
      '상디에고': 'San Diego',
      '상프란시스코': 'San Francisco',
      '카이로': 'Cairo',
      '이스탄불': 'Istanbul',
      '마드리드': 'Madrid',
      '베네치아': 'Venice',
      '아테네': 'Athens',
      '리스본': 'Lisbon',
      '상크리스토발': 'Santiago',
      '카사블랑카': 'Casablanca',
      '방콕': 'Bangkok',
      '하노이': 'Hanoi',
      '멜버른': 'Melbourne',
      '두바이': 'Dubai',
      '상파울루': 'São Paulo',
      '아프가나': 'Auckland',
      '프라하': 'Prague',
      '뮌헨': 'Munich',
      '톨레도': 'Toledo',
      '로마': 'Rome',
      '바르셀로나': 'Barcelona',
      '톰스크': 'Tomsk',
      '부다페스트': 'Budapest',
      '암스테르담': 'Amsterdam',
      '베네수엘라': 'Caracas',
      '몬트리올': 'Montreal',
      '프랑크푸르트': 'Frankfurt',
      '키예프': 'Kyiv',
      '헬싱크키': 'Helsinki',
      '카라치': 'Karachi',
      '발리': 'Bali',
      '칸쿤': 'Cancun',
      '도하': 'Doha',
      '오스틴': 'Austin',
      '시카고': 'Chicago',
      '밴쿠버': 'Vancouver',
      '리우데자네이루': 'Rio de Janeiro',
      '퀘백': 'Quebec City',
      '몬테비데오': 'Montevideo',
      '부에노스아이레스': 'Buenos Aires',
      '텔아비브': 'Tel Aviv',
      '무함마드': 'Marrakech',
      '퀸즐랜드': 'Queensland',
      '브리즈번': 'Brisbane',
      '퍼스': 'Perth',
      '마닐라': 'Manila',
      '제친': 'Cebu',
      '경주': 'Gyeongju',
      '목포': 'Mokpo',
      '순천': 'Suncheon',
      '전주': 'Jeonju',
      '오클랜드': 'Auckland',
      '퀸스타운': 'Queenstown',
      '팔마데마요르카': 'Palma de Mallorca',
      '발렌시아': 'Valencia',
      '홍콩': 'Hong Kong',
      '싱가포르': 'Singapore',
      '쿠알라룸푸르': 'Kuala Lumpur',
      '호치민시티': 'Ho Chi Minh City',
      '제다': 'Zadar',
      '더블린': 'Dublin',
      '헬싱키': 'Helsinki',
      '알마아타': 'Almaty',
      '아스타나': 'Nur-Sultan',
      '몬테카를로': 'Monte Carlo',
      '브에노스아이레스': 'Buenos Aires',
      '나이로비': 'Nairobi',
      '케이프타운': 'Cape Town',
      '델리': 'Delhi',
      '라스베이거스': 'Las Vegas',
      '몬트비데오': 'Montevideo',
      
    };
  
    return cityMapping[koreanCity] || koreanCity;
  };
  
  export default City;
  