const City = (koreanCity) => {
  const cityMapping = {
    서울: "Seoul",
    부산: "Busan",
    대구: "Daegu",
    인천: "Incheon",
    광주: "Gwangju",
    대전: "Daejeon",
    울산: "Ulsan",
    세종: "Sejong",
    구미: "Gumi",
    경산: "Gyeongsan",
    경기도: "Gyeonggi-do",
    강원도: "Gangwon-do",
    김천: "Gimcheon",
    문경: "Mungyeong",
    봉화군: "Bonghwa",
    상주시: "Sangju",
    성주군: "Seongju",
    안동: "Andong",

    충청북도: "Chungcheongbuk-do",
    충청남도: "Chungcheongnam-do",
    전라북도: "Jeollabuk-do",
    전라남도: "Jeollanam-do",
    경상북도: "Gyeongsangbuk-do",
    경상남도: "Gyeongsangnam-do",
    제주도: "Jeju-do",
    뉴욕: "New York",
    로스앤젤레스: "Los Angeles",
    런던: "London",
    파리: "Paris",
    도쿄: "Tokyo",
    오사카: "Osaka",
    후쿠오카: "Fukuoka",
    사포로: "Sapporo",
    교토: "Kyoto",
    구마모토: "Kumamoto",
    나라: "Nara",
    카가와: "Kagawa",
    토야마: "Toyama",
    히로시마: "Hiroshima",
    나하: "Naha",
    베를린: "Berlin",
    상파울로: "Sao Paulo",
    시드니: "Sydney",
    상하이: "Shanghai",
    모스크바: "Moscow",
    베이징: "Beijing",
    광저우: "Guangzhou",
    토론토: "Toronto",
    상트페테르부르크: "Saint Petersburg",
    뭄바이: "Mumbai",
    상디에고: "San Diego",
    상프란시스코: "San Francisco",
    카이로: "Cairo",
    이스탄불: "Istanbul",
    마드리드: "Madrid",
    베네치아: "Venice",
    아테네: "Athens",
    리스본: "Lisbon",
    상크리스토발: "Santiago",
    카사블랑카: "Casablanca",
    방콕: "Bangkok",
    하노이: "Hanoi",
    멜버른: "Melbourne",
    두바이: "Dubai",
    상파울루: "São Paulo",
    아프가나: "Auckland",
    프라하: "Prague",
    뮌헨: "Munich",
    톨레도: "Toledo",
    로마: "Rome",
    바르셀로나: "Barcelona",
    톰스크: "Tomsk",
    부다페스트: "Budapest",
    암스테르담: "Amsterdam",
    베네수엘라: "Caracas",
    몬트리올: "Montreal",
    프랑크푸르트: "Frankfurt",
    키예프: "Kyiv",
    헬싱크키: "Helsinki",
    카라치: "Karachi",
    발리: "Bali",
    칸쿤: "Cancun",
    도하: "Doha",
    오스틴: "Austin",
    시카고: "Chicago",
    밴쿠버: "Vancouver",
    리우데자네이루: "Rio de Janeiro",
    퀘백: "Quebec City",
    몬테비데오: "Montevideo",
    강진: "Gangjin",
    고흥: "Goheung",
    곡성: "Gokseong",
    광양: "Gwangyang",
    구례: "Gurye",
    나주: "Naju",
    담양: "Damyang",
    목포: "Mokpo",
    무안: "Mu'an",
    보성: "Boseong",
    순천: "Suncheon",
    신안: "Shin'an",
    여수: "Yeosu",
    영광: "Yeonggwang",
    영암: "Yeong'am",
    완도: "Wando",
    장성: "Jangseong",
    장흥: "Jangheung",
    진도: "Jindo",
    함평: "Hampyeong",
    해남: "Haenam",
    화순: "Hwansun",
    고창: "Gochang-gun",
    군산: "Gunsan-si",
    김제: "Gimje-si",
    남원: "Namwon-si",
    무주: "Muju-gun",
    부안: "Bu'an-gun",
    순창: "Sunchang-gun",
    완주: "Wanju-gun",
    익산: "Iksan-si",
    임실: "Imshil-gun",
    장수: "Jangsu-si",
    전주: "Jeonju-si",
    정읍: "Jeongeup-si",
    진안: "Jin'an-gun",
    금산: "Geumsan-gun",
    당진: "Dangjin-gun",
    부여: "Buyeo-gun",
    서산: "Seosan-si",
    서천: "Seocheon-gun",
    아산: "Asan-si",
    연기: "Yeongi-gun",
    예산: "Yesan-gun",
    천안: "Cheon'an-si",
    청양: "Cheongyang-gun",
    태안: "Tae'an-gun",
    홍성: "Hongseong-gun",
    괴산: "Gwoisan-gun",
    단양: "Danyang-gun",
    보은: "Bo'eun-gun",
    영동: "Yeongdong-gun",
    옥천: "Okcheon-gun",
    음성: "Umseong-gun",
    제천: "Jecheon-si",
    진천: "Jincheon-gun",
    청원: "Cheongwon-gun",
    청주: "Cheongju-si",
    충주: "Chungju-si",
  };

  return cityMapping[koreanCity] || koreanCity;
};

export default City;
